---
apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: inference-pr
spec:
  serviceAccountName: mlperf
  pipelineRef:
    name: inference-pl
  timeout: "0"
  resources:
  - name: repo
    resourceRef:
      name: inf-repo
  - name: build-image
    resourceRef:
      name: inf-build-image
  podTemplate:
    volumes:
    - name: inf-volume
      persistentVolumeClaim:
        claimName: od-pvc
